import os
from dotenv import load_dotenv

load_dotenv()

# LLM
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY")

# DARAJA
MPESA_CONSUMER_KEY = os.getenv("MPESA_CONSUMER_KEY")
MPESA_CONSUMER_SECRET = os.getenv("MPESA_CONSUMER_SECRET")
MPESA_PASSKEY = os.getenv("MPESA_PASSKEY") 
MPESA_CALLBACK_URL = os.getenv("MPESA_CALLBACK_URL")


#NEO4J
NEO4J_URI = os.getenv("NEO4J_URI")
NEO4J_USERNAME = os.getenv("NEO4J_USERNAME")
NEO4J_PASSWORD = os.getenv("NEO4J_PASSWORD")

# WHATSAPP
WHATSAPP_ACCESS_TOKEN=os.getenv("WHATSAPP_ACCESS_TOKEN")
WHATSAPP_APP_ID=os.getenv("WHATSAPP_APP_ID")
WHATSAPP_APP_SECRET=os.getenv("WHATSAPP_APP_SECRET")
VERSION='v18.0'
WHATSAPP_PHONE_NUMBER_ID=os.getenv("WHATSAPP_PHONE_NUMBER_ID")
WHATSAPP_VERIFICATION_TOKEN=os.getenv("WHATSAPP_VERIFICATION_TOKEN")


# TELEGRAM_BOT
TELEGRAM_BOT_TOKEN=os.getenv("TELEGRAM_BOT_TOKEN")


# Twitter/ X
TWITTER_USERNAME=os.getenv("TWITTER_USERNAME")
TWITTER_EMAIL=os.getenv("TWITTER_EMAIL")
TWITTER_PASSWORD=os.getenv("TWITTER_PASSWORD")


# VOICE AND VISUAL
# ELEVENLABS
ELEVENLABS_API_KEY=os.getenv("ELEVENLABS_API_KEY")


# DEEPGRAM
DEEPGRAM_API_KEY=os.getenv("DEEPGRAM_API_KEY")


# LANCHAIN

LANCHAIN_API_KEY=os.getenv("LANCHAIN_API_KEY")





#########################################
# BIGTOOLS API KEYS
#########################################

GOOGLE_API_KEY=os.getenv("GOOGLE_API_KEY")